sudo: required
services:
  - docker

before_install:
  - docker build -t mohsinasacha/multidocker -f ./client/Dockerfile.dev ./client

script:
  - docker run mohsinasacha/multidocker npm test -- --coverage

after_success: 
  - docker build -t mohsinasacha/multi-client ./client
  - docker build -t mohsinasacha/multi-server ./server
  - docker build -t mohsinasacha/multi-worker ./worker
  - docker build -t mohsinasacha/multi-nginx ./nginx

  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Push the images to docker hub
  - docker push mohsinasacha/multi-client
  - docker push mohsinasacha/multi-server
  - docker push mohsinasacha/multi-worker
  - docker push mohsinasacha/multi-nginx

deploy: 
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-542629978269
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY